source "https://rubygems.org"
gem "jekyll"
gem "minima"
group :jekyll_plugins do
  gem "jekyll-feed"
end
platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1", :platforms => [:windows]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
